### ISSUE TITLE
Change instruction to checkout a branch

### ISSUE THREAD

**Issue by laurentheirendt** [uni-lu/group_members#5]
It would probably be more instructive to have:
```bash
git checkout -b your_github_login_BRANCH
```
(or something similar) instead of
```bash
git checkout -b your_github_login
```

**Comment by uni-lu** [comment]
Not sure I like that. I see the point though!

**Comment by laurentheirendt** [comment]
May we have a different name then? For now, I find it quite confusing to submit a PR and then see
```
your_github_login:your_github_login
```

**Comment by uni-lu** [comment]
What about a `practice` branch?

**Comment by laurentheirendt** [comment]
`homework` branch as discussed.
